rpc_url: https://api.mainnet-beta.solana.com
wallets:
  - 7MBqSoh7dBnB1c3ZHEvW7hXhXQMKGuFxL1b9z3qZFEFv
  - 6pZMz6S2xFzQX8d3EepDmj1YKgcwA7MeBXYLsRb8nDdy
  - 5E2iqsoLkUpRQfD4Tuk6msr3kK4GVD5BBU9xKaKZMi1o
  - 3i9pT6F4i9DSoAZ74t6Rk1SK5yLgkzftAKk7KkmMBmrB